#! /bin/sh

PREREQ=""
DESCRIPTION="Sleeping for 5 seconds before starting systemd..."

prereqs()
{
       echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
       prereqs
       exit 0
       ;;
esac

. /scripts/casper-functions

log_begin_msg "$DESCRIPTION"

sleep 5

log_end_msg
