#!/bin/bash

# First, make sure sshd is okay.
dpkg-reconfigure openssh-server
# This will either generate keys or if they already exist, restart sshd

# Get into our main directory for it to be the CWD for the rest.
cd /home/git/
KDHOME="/home/git/kamikazi-deploy"
KDRES="${KDHOME}/resources"

MYNAME=$(hostname)
echo -n "kamikazi-role-dummy: We are: ${MYNAME}"

echo "kamikazi-role-dummy: I am the dummy, responsible for debugging."
echo -e '{\n  "role": "dummy"\n}\n' > ${KDRES}/serf/config-role.json
sync; sync; sync;
echo "kamikazi-role-dummy: Restarting serf agent to change role."
service serf restart
echo "kamikazi-role-dummy: Enabling swap for dummy."
swapon -a
echo "kamikazi-role-dummy: dummy role should be active."

