#!/bin/bash

# V0.5.0 runs this a minute after kamikazi-boot.sh to specialize a system for a task.

# First, make sure sshd is okay.
dpkg-reconfigure openssh-server
# This will either generate keys or if they already exist, restart sshd

# Get into our main directory for it to be the CWD for the rest.
cd /home/git/
KDHOME="/home/git/kamikazi-deploy"
KDRES="${KDHOME}/resources"

MYNAME=$(hostname)
echo -n "kamikazi-role-firewall: We are: ${MYNAME}"

if [ "${MYNAME}" == "firewall" ]; then
    echo "kamikazi-role-firewall: I am the firewall, responsible for networking."
    echo -e '{\n  "role": "firewall"\n}\n' > ${KDRES}/serf/config-role.json
    sync; sync; sync;
    echo "kamikazi-role-firewall: Restarting serf agent to change role."
    service serf restart
    echo "kamikazi-role-firewall: Enabling swap for firewall."
    swapon -a
    echo "kamikazi-role-firewall: Enabling btrfs volume 'firewall'."
    echo 'LABEL="firewall" /srv btrfs subvol=storage 0 0' >> /etc/fstab
    btrfs device scan  # This should fix the ctree error.
    mount /srv
    echo "kamikazi-role-firewall: Enabling RethinkDB instance 'wanfirewall'."
    cp ${KDRES}/rethink/wanfirewall.conf /etc/rethinkdb/instances.d/wanfirewall.conf
    chown -R rethinkdb.rethinkdb /var/lib/rethinkdb
    sync
    sleep 1
    service rethinkdb start
    echo "kamikazi-role-firewall: RethinkDB instance 'wanfirewall' is up"
    echo "kamikazi-role-firewall: firewall should be active."
fi

