#! /bin/sh

PREREQ=""
DESCRIPTION="Setting dbus machine-id..."

prereqs()
{
       echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
       prereqs
       exit 0
       ;;
esac

. /scripts/casper-functions

log_begin_msg "$DESCRIPTION"

# Set the machine-id very early if a file exists on isodevice.
if [ -d /root/isodevice/boot/config ]; then
    if [ -f /root/isodevice/boot/config/machine-id ]; then
        cp /root/isodevice/boot/config/machine-id /root/var/lib/dbus/machine-id
    fi
fi

log_end_msg
