#!/bin/sh -e
# Script to dispatch NetworkManager events
#
# Runs ifupdown scripts when NetworkManager fiddles with interfaces.
# See NetworkManager(8) for further documentation of the dispatcher events.

if [ -z "$1" ]; then
    echo "$0: called with no interface" 1>&2
    exit 1;
fi

# Fake ifupdown environment
export IFACE="$1"
export LOGICAL="$1"
export ADDRFAM="NetworkManager"
export METHOD="NetworkManager"
export VERBOSITY="0"

# Run the right scripts
case "$2" in
    down|vpn-down|dhcp6-change)
        # Do nothing
	;;
    up|vpn-up|hostname|dhcp4-change)
        echo "NM-hostname: event ${2} on ${IFACE}, new hostname: '${DHCP4_HOST_NAME}'" >> /var/log/nm-hostname.log
        procenv -e >> /var/log/nm-hostname.log
        echo "==============================" >> /var/log/nm-hostname.log
        echo ${DHCP4_HOST_NAME} >> /etc/hostname
        hostname ${DHCP4_HOST_NAME}
	;;
    *)
	echo "$0: called with unknown action \`$2'" 1>&2
	exit 1
	;;
esac
