#! /bin/sh

PREREQ=""
DESCRIPTION="Setting up openssh-server host keys..."

prereqs()
{
       echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
       prereqs
       exit 0
       ;;
esac

. /scripts/casper-functions

log_begin_msg "$DESCRIPTION"

# Set the SSH Host keys very early if they exist on isodevice.
if [ -d /root/isodevice/boot/config/ssh ]; then
    if [ -f /root/isodevice/boot/config/ssh/ssh_host_ecdsa_key ]; then
        cp /root/isodevice/boot/config/ssh/ssh_host_* /root/etc/ssh/
    fi
fi

log_end_msg
