#! /bin/sh

PREREQ=""
DESCRIPTION="Setting hostname..."

prereqs()
{
       echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
       prereqs
       exit 0
       ;;
esac

. /scripts/casper-functions

log_begin_msg "$DESCRIPTION"

# Set the hostname very early if a file exists on isodevice.
if [ -d /root/isodevice/boot/config ]; then
    if [ -f /root/isodevice/boot/config/hostname ]; then
        FROMFILE=$(cat /root/isodevice/boot/config/hostname)
        if [ "${FROMFILE}" != "${HOST}" ]; then
            HOST=${FROMFILE}
        fi
    fi
fi

echo "$HOST" > /root/etc/hostname
cat > /root/etc/hosts <<EOF
127.0.0.1 localhost
127.0.1.1 $HOST

# The following lines are desirable for IPv6 capable hosts
::1     ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
ff02::3 ip6-allhosts

EOF
hostname "$HOST"

log_end_msg
