#!/bin/sh

PREREQ=""

prereqs()
{
	echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
	prereqs
	exit 0
	;;
esac

# blacklist vga16fb when vga= or video= given
for x in $(cat /proc/cmdline); do
        case ${x} in
	vga=*|video=*)
		echo "blacklist vga16fb" >> /etc/modprobe.d/initramfs.conf
		;;
	esac
done

# -- Kamilion
# Disable loading mptsas automatically on boot.
echo "blacklist mptsas" >> /etc/modprobe.d/initramfs.conf
# -- Kamilion
# Disable loading mpt2sas automatically on boot.
echo "blacklist mpt2sas" >> /etc/modprobe.d/initramfs.conf
# -- Kamilion
# Disable loading mpt3sas automatically on boot.
echo "blacklist mpt3sas" >> /etc/modprobe.d/initramfs.conf
# -- Kamilion
# Disable loading 3w_9xxx automatically on boot.
echo "blacklist 3w_9xxx" >> /etc/modprobe.d/initramfs.conf
# -- Kamilion
# Disable loading 3w-sas automatically on boot.
echo "blacklist 3w-sas" >> /etc/modprobe.d/initramfs.conf
# -- Kamilion
# Disable loading aacraid automatically on boot.
echo "blacklist aacraid" >> /etc/modprobe.d/initramfs.conf
# -- Kamilion


# sanity check
[ -z "${blacklist}" ] && exit 0

# write blacklist to modprobe.d
IFS=','
for b in ${blacklist}; do
	echo "blacklist $b" >> /etc/modprobe.d/initramfs.conf
done
