#!/bin/bash

# First, make sure sshd is okay.
dpkg-reconfigure openssh-server
# This will either generate keys or if they already exist, restart sshd

# Get into our main directory for it to be the CWD for the rest.
cd /home/git/
KDHOME="/home/git/kamikazi-deploy"
KDRES="${KDHOME}/resources"

MYNAME=$(hostname)
echo -n "kamikazi-role-cloudmaster: We are: ${MYNAME}"

if [ "${MYNAME}" == "cloudmaster" ]; then
    echo "kamikazi-role-cloudmaster: I am the cloudmaster, responsible for data storage."
    # Change the role in the configuration file, in case serf restarts on it's own.
    echo -e '{\n  "role": "cloudmaster"\n}\n' > ${KDRES}/serf/config-role.json
    sync; sync; sync;
    echo "kamikazi-role-cloudmaster: Instructing serf agent to change role."
    serf tags -set role=cloudmaster
    echo "kamikazi-role-cloudmaster: Enabling swap for cloudmaster."
    swapon -a
    echo "kamikazi-role-cloudmaster: Enabling ceph for cloudmaster."
    service ceph-all stop
    sleep 10
    service ceph-all start
    while ! ceph health | grep -q 'HEALTH_OK'; do
      echo "kamikazi-role-cloudmaster: Cloudmaster waiting for ceph..."
      sleep 5;
    done

    #echo "kamikazi-role-cloudmaster: Copying ISO to ram to serve updates for outdated actors."
    #cp /isodevice/boot/isos/kamikazi.iso /tmp/kamikazi.iso
    #sync
    echo "kamikazi-role-cloudmaster: Enabling btrfs volume 'cloudmaster'."
    mount -v /mnt/btrfs/cloudmaster
    echo "kamikazi-role-cloudmaster: Enabling RethinkDB instance 'wancloudmaster'."
    cp ${KDRES}/rethink/cloudmaster.conf /etc/rethinkdb/instances.d/cloudmaster.conf
    chown -R rethinkdb.rethinkdb /var/lib/rethinkdb
    sync
    sleep 1
    service rethinkdb start
    echo "kamikazi-role-cloudmaster: RethinkDB instance 'cloudmaster' is up"
    echo "kamikazi-role-cloudmaster: Disabling diskmonitor for cloudmaster."
    supervisorctl stop kamikazi-diskmonitor
    echo "kamikazi-role-cloudmaster: Disabling diskworker for cloudmaster."
    supervisorctl stop kamikazi-diskworker
    echo "kamikazi-role-cloudmaster: Cloudmaster should be active."
fi

